import img1 from "../Assets/Images/sneakers/shoe1.jpg"
import img2 from "../Assets/Images/sneakers/shoe2.jpg"
import img3 from "../Assets/Images/sneakers/shoe3.jpg"
import img4 from "../Assets/Images/sneakers/shoe4.jpg"

export const data = [
   {
      id: 0,
      title: `LITE RACER ADAPT 3.0 SHOES`,
      description: `Whether your little one is meeting friends in the park or heading to school in the morning, these kids' slip-on shoes make it easy for them to get out the door and into their day. The sock-like fit and cushioned midsole keep feet comfortable for all-day play, and adidas logos and stretch laces complete the look.`,
      specifications: ["Regular fit", "Slip-on construction", "Textile upper", "Sock-like feel", "Lightweight slip-on shoes", "Cushioned Cloudfoam midsole and textile lining", "Imported", "Product color: Core Black / Core Black / Victory Crimson", "Product code: GZ7987"],
      price: `$31`,
      category: `Women's Running`,
      image: img1,
   },
   {
      id: 1,
      title: `LITE RACER ADAPT 3.0 SHOES`,
      description: `Whether your little one is meeting friends in the park or heading to school in the morning, these kids' slip-on shoes make it easy for them to get out the door and into their day. The sock-like fit and cushioned midsole keep feet comfortable for all-day play, and adidas logos and stretch laces complete the look.`,
      specifications: ["Regular fit", "Slip-on construction", "Textile upper", "Sock-like feel", "Lightweight slip-on shoes", "Cushioned Cloudfoam midsole and textile lining", "Imported", "Product color: Core Black / Core Black / Victory Crimson", "Product code: GZ7987"],
      price: `$42`,
      category: `Men's Running`,
      image: img2,
   },
   {
      id: 2,
      title: `LITE RACER ADAPT 3.0 SHOES`,
      description: `Whether your little one is meeting friends in the park or heading to school in the morning, these kids' slip-on shoes make it easy for them to get out the door and into their day. The sock-like fit and cushioned midsole keep feet comfortable for all-day play, and adidas logos and stretch laces complete the look.`,
      specifications: ["Regular fit", "Slip-on construction", "Textile upper", "Sock-like feel", "Lightweight slip-on shoes", "Cushioned Cloudfoam midsole and textile lining", "Imported", "Product color: Core Black / Core Black / Victory Crimson", "Product code: GZ7987"],
      price: `$28`,
      category: `Women's Running`,
      image: img3,
   },
   {
      id: 3,
      title: `LITE RACER ADAPT 3.0 SHOES`,
      description: `Whether your little one is meeting friends in the park or heading to school in the morning, these kids' slip-on shoes make it easy for them to get out the door and into their day. The sock-like fit and cushioned midsole keep feet comfortable for all-day play, and adidas logos and stretch laces complete the look.`,
      specifications: ["Regular fit", "Slip-on construction", "Textile upper", "Sock-like feel", "Lightweight slip-on shoes", "Cushioned Cloudfoam midsole and textile lining", "Imported", "Product color: Core Black / Core Black / Victory Crimson", "Product code: GZ7987"],
      price: `$36`,
      category: `Men's Running`,
      image: img4,
   },
   {
      id: 4,
      title: `LITE RACER ADAPT 3.0 SHOES`,
      description: `Whether your little one is meeting friends in the park or heading to school in the morning, these kids' slip-on shoes make it easy for them to get out the door and into their day. The sock-like fit and cushioned midsole keep feet comfortable for all-day play, and adidas logos and stretch laces complete the look.`,
      specifications: ["Regular fit", "Slip-on construction", "Textile upper", "Sock-like feel", "Lightweight slip-on shoes", "Cushioned Cloudfoam midsole and textile lining", "Imported", "Product color: Core Black / Core Black / Victory Crimson", "Product code: GZ7987"],
      price: `$31`,
      category: `Women's Essential`,
      image: img1,
   },
   {
      id: 5,
      title: `LITE RACER ADAPT 3.0 SHOES`,
      description: `Whether your little one is meeting friends in the park or heading to school in the morning, these kids' slip-on shoes make it easy for them to get out the door and into their day. The sock-like fit and cushioned midsole keep feet comfortable for all-day play, and adidas logos and stretch laces complete the look.`,
      specifications: ["Regular fit", "Slip-on construction", "Textile upper", "Sock-like feel", "Lightweight slip-on shoes", "Cushioned Cloudfoam midsole and textile lining", "Imported", "Product color: Core Black / Core Black / Victory Crimson", "Product code: GZ7987"],
      price: `$31`,
      category: `Men's Essential`,
      image: img2,
   },
   {
      id: 6,
      title: `LITE RACER ADAPT 3.0 SHOES`,
      description: `Whether your little one is meeting friends in the park or heading to school in the morning, these kids' slip-on shoes make it easy for them to get out the door and into their day. The sock-like fit and cushioned midsole keep feet comfortable for all-day play, and adidas logos and stretch laces complete the look.`,
      specifications: ["Regular fit", "Slip-on construction", "Textile upper", "Sock-like feel", "Lightweight slip-on shoes", "Cushioned Cloudfoam midsole and textile lining", "Imported", "Product color: Core Black / Core Black / Victory Crimson", "Product code: GZ7987"],
      price: `$31`,
      category: `Men's Essential`,
      image: img3,
   },
   {
      id: 7,
      title: `LITE RACER ADAPT 3.0 SHOES`,
      description: `Whether your little one is meeting friends in the park or heading to school in the morning, these kids' slip-on shoes make it easy for them to get out the door and into their day. The sock-like fit and cushioned midsole keep feet comfortable for all-day play, and adidas logos and stretch laces complete the look.`,
      specifications: ["Regular fit", "Slip-on construction", "Textile upper", "Sock-like feel", "Lightweight slip-on shoes", "Cushioned Cloudfoam midsole and textile lining", "Imported", "Product color: Core Black / Core Black / Victory Crimson", "Product code: GZ7987"],
      price: `$31`,
      category: `Women's Essential`,
      image: img4,
   },
   {
      id: 8,
      title: `LITE RACER ADAPT 3.0 SHOES`,
      description: `Whether your little one is meeting friends in the park or heading to school in the morning, these kids' slip-on shoes make it easy for them to get out the door and into their day. The sock-like fit and cushioned midsole keep feet comfortable for all-day play, and adidas logos and stretch laces complete the look.`,
      specifications: ["Regular fit", "Slip-on construction", "Textile upper", "Sock-like feel", "Lightweight slip-on shoes", "Cushioned Cloudfoam midsole and textile lining", "Imported", "Product color: Core Black / Core Black / Victory Crimson", "Product code: GZ7987"],
      price: `$31`,
      category: `Women's Running`,
      image: img1,
   },
   {
      id: 9,
      title: `LITE RACER ADAPT 3.0 SHOES`,
      description: `Whether your little one is meeting friends in the park or heading to school in the morning, these kids' slip-on shoes make it easy for them to get out the door and into their day. The sock-like fit and cushioned midsole keep feet comfortable for all-day play, and adidas logos and stretch laces complete the look.`,
      specifications: ["Regular fit", "Slip-on construction", "Textile upper", "Sock-like feel", "Lightweight slip-on shoes", "Cushioned Cloudfoam midsole and textile lining", "Imported", "Product color: Core Black / Core Black / Victory Crimson", "Product code: GZ7987"],
      price: `$31`,
      category: `Men's Running`,
      image: img2,
   },
   {
      id: 10,
      title: `LITE RACER ADAPT 3.0 SHOES`,
      description: `Whether your little one is meeting friends in the park or heading to school in the morning, these kids' slip-on shoes make it easy for them to get out the door and into their day. The sock-like fit and cushioned midsole keep feet comfortable for all-day play, and adidas logos and stretch laces complete the look.`,
      specifications: ["Regular fit", "Slip-on construction", "Textile upper", "Sock-like feel", "Lightweight slip-on shoes", "Cushioned Cloudfoam midsole and textile lining", "Imported", "Product color: Core Black / Core Black / Victory Crimson", "Product code: GZ7987"],
      price: `$31`,
      category: `Original`,
      image: img3,
   },
   {
      id: 11,
      title: `LITE RACER ADAPT 3.0 SHOES`,
      description: `Whether your little one is meeting friends in the park or heading to school in the morning, these kids' slip-on shoes make it easy for them to get out the door and into their day. The sock-like fit and cushioned midsole keep feet comfortable for all-day play, and adidas logos and stretch laces complete the look.`,
      specifications: ["Regular fit", "Slip-on construction", "Textile upper", "Sock-like feel", "Lightweight slip-on shoes", "Cushioned Cloudfoam midsole and textile lining", "Imported", "Product color: Core Black / Core Black / Victory Crimson", "Product code: GZ7987"],
      price: `$31`,
      category: `Original`,
      image: img4,
   },
]